import { HomeBanner } from "@/Banner/HomeBanner";
import HomeSection from "@/Section/HomeSection";
import HomeAbout from "@/Section/HomeSection/HomeBook";
import Homegallery from "@/Section/HomeSection/Homespecialities";
import HomePromise from "@/Section/HomeSection/HomeDoctors";
import HomeService from "@/Section/HomeSection/HomeContact";
import Head from "next/head";
import { HomeFooter } from "@/Layout/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hospital</title>
        <meta name="description" content="Generated by Hospital" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HomeSection />
        <HomeFooter /> 
      </div>
    </>
  );
}
